version: '3.8'

services:
  server:
    build: .
    command: npm run server
    container_name: pokemon-server
    image: node:17-alpine

    ports:
      - 3000:3000
    volumes:
      - .:/app

  postgres:
    container_name: pokemon-database
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
